AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A minimal no-op SAM template for testing pipeline deployment

Resources:
  NoOpResource:
    Type: AWS::CloudFormation::WaitConditionHandle
