name: Auto-merge Dependabot PRs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    name: Enable auto-merge on Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Auto-approve Dependabot PR
        uses: hmarr/auto-approve-action@v3
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
